apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sf
  template:
    metadata:
      labels:
        app: nginx-sf
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
      worker_connections 10240;
    }
    http {
      server {
        listen 80;
        server_name localhost;
        location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
        }
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: sf-webserver
spec:
  selector:
    app: nginx-sf
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

